//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xram_KR51.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public int id_doljnost { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string number_phone { get; set; }
        public string passport { get; set; }
        public string data { get; set; }
        public string vxod { get; set; }
        public string type_vxod { get; set; }
        public int id_pol { get; set; }
    
        public virtual id_doljnost id_doljnost1 { get; set; }
        public virtual id_Pol id_Pol1 { get; set; }
    }
}
